---
title: "Effectiveness of Drug Trafficking Legislation in Southern America"
author: "Tommy O'Neil"
description: "City-level effectiveness of drug trafficking legislation within Colombia and Brazil"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to different pieces of legislation that have been passed over the past decade in response to massive drug flow within certain Southern American countries. I want to test the levels of violent crime that are correlated within these highly trafficked areas and see if there is a correlation between the legislation being passed and any tangible effect that it has on these statistics. I plan on looking at multiple cities across these countries to see if there is differing data based on the specific urban center that is being looked at. 

The two variables I want to investigate are levels of violent crime versus time legislation is passed. I think the other route I could take would be level of drugs being trafficked as well but this may be a bit more difficult to get specific data on. 



